language: python
python: 3.7
sudo: false

install:
- pip install -e .
- pip install -U pytest

script:
- env AWS_DEFAULT_REGION=us-west-2 pytest tests

deploy:
  skip_cleanup: true
  provider: pypi
  user: ajenkins
  password:
    secure: "YVLV0uthgB2MMlW4CsTrymGerHJ6tN5I9Vdk3oFB+VeML5mDVlRzg2jpD7RORIRD1SsEsg2YKEWY0OTqWSIbMnIa7iV9nbeY3sdM8qSzPTQ7WuANVUB/W7K0BIpM3RIaF2RyTDbfOjtQU9nkRNhUDTwoFoATRBI9PJ6zbKY/xvOiGQKanaMqKSaHFb4xMpmUbk1xpqg4mwa/fQWil4O5Ht2boMiIqIO6kDwCR+RhoO/y0V9ux4oDe3HZCUTwOsEWHP+bD2Nu+x052FfUh8t0FTT6td8VT4vwi/y1uz6CtZ9u+baFT9m0bAFXxb1UpwaBhuS5/yki3l0IOYPbn9dC6RV78i5cFeZ9+D5fuvBeUou470RHgnB5ek/Rrp6tltFm8eZPLgmtMWwKtAobYft/ZTHNGBRo2rHBfkNJF/tXnj4aFSD6V9QPUNtcSvXbGi0f4upagFteYadhlv5SRGrkFjhPoslrfTFpsg1ffcHodzc7PQde/Yvllp9mzPuG0/SJIL5yaZJW9DPK8negmTrwqIA/ejIZ9maaanTGsND8H3LDAZYCtYOIkP+B7beYPn1ZV5pglXHCufeW700n1p9Q54mphy88aQXqqUMSDUlC5zKj77hocCJLeoQYR4eIU1bCCU9G/aVetsxPRtDUA0SoB7uJqMxoSuzc5Tj/uRy+p04="
  on:
    tags: true
    repo: ajenkins-cargometrics/pyflow
